In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 105],
    "Name": [" Amit ", "Sneha", "RAHUL", "Priya ", "Vikas", "Vikas"],
    "Department": [
        "Data", "data", "IT", "HR", "IT", "IT"
    ],
    "Salary": [
        70000, 85000, np.nan, 55000, 75000, 75000
    ],
    "Experience": [
        2, 3, np.nan, 2, 3, 3
    ]
}

df = pd.DataFrame(data)

In [4]:
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT      NaN         NaN
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Detect Missing Values

In [7]:
df.isna()

   Employee_ID   Name  Department  Salary  Experience
0        False  False       False   False       False
1        False  False       False   False       False
2        False  False       False    True        True
3        False  False       False   False       False
4        False  False       False   False       False
5        False  False       False   False       False

Count Missing Values

In [8]:
df.isna().sum()

Employee_ID    0
Name           0
Department     0
Salary         1
Experience     1
dtype: int64

isnull()

In [10]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Salary         1
Experience     1
dtype: int64

Find Rows Containing Missing Values

In [11]:
df[df.isna().any(axis=1)]

   Employee_ID   Name Department  Salary  Experience
2          103  RAHUL         IT     NaN         NaN

Find Rows With No Missing Values

In [12]:
df[df.notna().all(axis=1)]

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

notna() → is this value present?\
all(axis=1) → are ALL values in this row present?

Remove Rows With Missing Data

In [13]:
clean_df = df.dropna()
print(clean_df)

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Remove Only Rows Where Specific Column Is Missing

In [14]:
clean_df = df.dropna(
    subset=["Salary"]
)
clean_df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Fill Missing Values

In [16]:
average_salary = df["Salary"].mean()
print(average_salary)

72000.0

In [17]:
df["Salary"] = df["Salary"].fillna(
    average_salary
)

In [18]:
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT  72000.0         NaN
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Fill With Median

In [23]:
median_experience = df["Experience"].median()
df["Experience"] = df["Experience"].fillna(median_experience)
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT  72000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Forward Fill

In [25]:
df["Salary"] = df["Salary"].ffill()
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT  72000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Backward Fill

In [26]:
df["Salary"] = df["Salary"].bfill()
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT  72000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0
5          105   Vikas         IT  75000.0         3.0

Find Duplicate Rows

In [27]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

Count Duplicates

In [28]:
df.duplicated().sum()

np.int64(1)

Remove Duplicates

In [29]:
df = df.drop_duplicates()
df

   Employee_ID    Name Department   Salary  Experience
0          101   Amit        Data  70000.0         2.0
1          102   Sneha       data  85000.0         3.0
2          103   RAHUL         IT  72000.0         3.0
3          104  Priya          HR  55000.0         2.0
4          105   Vikas         IT  75000.0         3.0

Duplicate Based on One Column

In [30]:
print(
    df.duplicated(
        subset=["Employee_ID"]
    )
)

0    False
1    False
2    False
3    False
4    False
dtype: bool

Clean Text — str.strip()

In [32]:
df["Name"] = df["Name"].str.strip()
df

   Employee_ID   Name Department   Salary  Experience
0          101   Amit       Data  70000.0         2.0
1          102  Sneha       data  85000.0         3.0
2          103  RAHUL         IT  72000.0         3.0
3          104  Priya         HR  55000.0         2.0
4          105  Vikas         IT  75000.0         3.0

Standardize Capitalization

In [33]:
df["Name"] = df["Name"].str.title()
df

   Employee_ID   Name Department   Salary  Experience
0          101   Amit       Data  70000.0         2.0
1          102  Sneha       data  85000.0         3.0
2          103  Rahul         IT  72000.0         3.0
3          104  Priya         HR  55000.0         2.0
4          105  Vikas         IT  75000.0         3.0

Standardize Department

In [35]:
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
)
df

   Employee_ID   Name Department   Salary  Experience
0          101   Amit       DATA  70000.0         2.0
1          102  Sneha       DATA  85000.0         3.0
2          103  Rahul         IT  72000.0         3.0
3          104  Priya         HR  55000.0         2.0
4          105  Vikas         IT  75000.0         3.0

Replace Values

In [36]:
df["Department"] = df["Department"].replace({
    "data": "Data",
    "DATA": "Data",
    "it": "IT"
})

Check Unique Values

In [37]:
df["Department"].unique()

<StringArray>
['Data', 'IT', 'HR']
Length: 3, dtype: str

In [38]:
df["Department"].nunique()

3

Data Types

In [40]:
df.dtypes

Employee_ID      int64
Name               str
Department         str
Salary         float64
Experience     float64
dtype: object

Convert Data Type

In [43]:
df["Experience"] = df["Experience"].astype(int)

In [44]:
df.dtypes

Employee_ID      int64
Name               str
Department         str
Salary         float64
Experience       int64
dtype: object

Rename Columns

In [46]:
df = df.rename(
    columns = {
        "Employee_ID" : "EmployeeID"
    }
)
df

   EmployeeID   Name Department   Salary  Experience
0         101   Amit       Data  70000.0           2
1         102  Sneha       Data  85000.0           3
2         103  Rahul         IT  72000.0           3
3         104  Priya         HR  55000.0           2
4         105  Vikas         IT  75000.0           3

Detect Invalid Values\
Suppose salary contains:\
70000\
85000\
-5000\
55000

In [47]:
invalid_salary = df[
    df["Salary"] < 0
]
print(invalid_salary)

Empty DataFrame
Columns: [EmployeeID, Name, Department, Salary, Experience]
Index: []