In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Customer_ID": [
        101, 102, 103, 104, 105, 105, 106, 107
    ],

    "Name": [
        " Amit ", "SNEHA", " Rahul",
        "Priya ", "vikas", "vikas",
        " NEHA ", "Arjun"
    ],

    "City": [
        "Pune", "mumbai", "PUNE",
        "Delhi", "Mumbai", "Mumbai",
        None, "Delhi"
    ],

    "Age": [
        24, 27, np.nan,
        31, 29, 29,
        26, np.nan
    ],

    "Salary": [
        50000, 65000, 55000,
        np.nan, 72000, 72000,
        60000, 48000
    ]
}

df = pd.DataFrame(data)

In [4]:
df

   Customer_ID    Name    City   Age   Salary
0          101   Amit     Pune  24.0  50000.0
1          102   SNEHA  mumbai  27.0  65000.0
2          103   Rahul    PUNE   NaN  55000.0
3          104  Priya    Delhi  31.0      NaN
4          105   vikas  Mumbai  29.0  72000.0
5          105   vikas  Mumbai  29.0  72000.0
6          106   NEHA      NaN  26.0  60000.0
7          107   Arjun   Delhi   NaN  48000.0

1. Inspect

In [6]:
df.shape

(8, 5)

In [8]:
df.columns

Index(['Customer_ID', 'Name', 'City', 'Age', 'Salary'], dtype='str')

In [11]:
df.dtypes

Customer_ID      int64
Name               str
City               str
Age            float64
Salary         float64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  8 non-null      int64
 1   Name         8 non-null      str
 2   City         7 non-null      str
 3   Age          6 non-null      float64
 4   Salary       7 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 452.0 bytes

2. Missing Values

In [18]:
df.isna()

   Customer_ID   Name   City    Age  Salary
0        False  False  False  False   False
1        False  False  False  False   False
2        False  False  False   True   False
3        False  False  False  False    True
4        False  False  False  False   False
5        False  False  False  False   False
6        False  False   True  False   False
7        False  False  False   True   False

In [19]:
df.isna().sum()

Customer_ID    0
Name           0
City           1
Age            2
Salary         1
dtype: int64

3. Duplicates

In [22]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [30]:
df = df.drop_duplicates()

4. Clean Names

In [31]:
df["Name"] = df["Name"].str.strip().str.title()

In [32]:
df

   Customer_ID   Name    City   Age   Salary
0          101   Amit    Pune  24.0  50000.0
1          102  Sneha  mumbai  27.0  65000.0
2          103  Rahul    PUNE   NaN  55000.0
3          104  Priya   Delhi  31.0      NaN
4          105  Vikas  Mumbai  29.0  72000.0
6          106   Neha     NaN  26.0  60000.0
7          107  Arjun   Delhi   NaN  48000.0

Clean Cities

In [33]:
df["City"] = df["City"].str.strip().str.title()

In [34]:
df

   Customer_ID   Name    City   Age   Salary
0          101   Amit    Pune  24.0  50000.0
1          102  Sneha  Mumbai  27.0  65000.0
2          103  Rahul    Pune   NaN  55000.0
3          104  Priya   Delhi  31.0      NaN
4          105  Vikas  Mumbai  29.0  72000.0
6          106   Neha     NaN  26.0  60000.0
7          107  Arjun   Delhi   NaN  48000.0

Handle City

In [52]:
df["City"] = df["City"].ffill()

In [53]:
df

   Customer_ID   Name    City  Age        Salary
0          101   Amit    Pune   24  50000.000000
1          102  Sneha  Mumbai   27  65000.000000
2          103  Rahul    Pune   27  55000.000000
3          104  Priya   Delhi   31  58333.333333
4          105  Vikas  Mumbai   29  72000.000000
6          106   Neha  Mumbai   26  60000.000000
7          107  Arjun   Delhi   27  48000.000000

Handle Age

In [36]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [37]:
df

   Customer_ID   Name    City   Age   Salary
0          101   Amit    Pune  24.0  50000.0
1          102  Sneha  Mumbai  27.0  65000.0
2          103  Rahul    Pune  27.0  55000.0
3          104  Priya   Delhi  31.0      NaN
4          105  Vikas  Mumbai  29.0  72000.0
6          106   Neha     NaN  26.0  60000.0
7          107  Arjun   Delhi  27.0  48000.0

Handle Salary

In [45]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [46]:
df

   Customer_ID   Name    City   Age        Salary
0          101   Amit    Pune  24.0  50000.000000
1          102  Sneha  Mumbai  27.0  65000.000000
2          103  Rahul    Pune  27.0  55000.000000
3          104  Priya   Delhi  31.0  58333.333333
4          105  Vikas  Mumbai  29.0  72000.000000
6          106   Neha     NaN  26.0  60000.000000
7          107  Arjun   Delhi  27.0  48000.000000

Data Types

In [48]:
df["Age"] = df["Age"].astype(int)

In [49]:
df.dtypes

Customer_ID      int64
Name               str
City               str
Age              int64
Salary         float64
dtype: object

Validation

In [54]:
df.isna().sum()

Customer_ID    0
Name           0
City           0
Age            0
Salary         0
dtype: int64

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df["City"].unique()

<StringArray>
['Pune', 'Mumbai', 'Delhi']
Length: 3, dtype: str

In [57]:
df["Name"].unique()

<StringArray>
['Amit', 'Sneha', 'Rahul', 'Priya', 'Vikas', 'Neha', 'Arjun']
Length: 7, dtype: str

In [58]:
df.dtypes

Customer_ID      int64
Name               str
City               str
Age              int64
Salary         float64
dtype: object

Bonus

Which city has the highest average salary?

In [61]:
highest_avg_salary = df.groupby("City")["Salary"].mean().idxmax()

In [62]:
highest_avg_salary

'Mumbai'

Which city has the most customers?

In [72]:
city_count = df.groupby("City")["Customer_ID"].count()

most_customer_city = city_count.idxmax()

print(most_customer_city)

Mumbai

Who is the highest-paid customer?

In [78]:
highest_paid_cust = df["Salary"].idxmax()

print(df.loc[highest_paid_cust, "Name"])

Vikas

What is the average age?

In [81]:
print(round(df["Age"].mean(), 2))

27.29

Final Report:

In [98]:
print("=" * 50)
print("CUSTOMER DATA REPORT")
print("=" * 50)

total_cust = df["Customer_ID"].count()
avg_age = round(df["Age"].mean(), 2)
avg_salary = round(df["Salary"].mean(), 2)

print("\nTotal Customers:",total_cust)
print("Average Age:",avg_age)
print("Average Salary:",avg_salary)

highest_salary = df["Salary"].max()
highest_paid_cust = df["Salary"].idxmax()
cust_name = df.loc[highest_paid_cust, "Name"]

print("\nHighest Salary:",highest_salary)
print("Highest Paid Customer:",cust_name)

highest_paying_city = df.groupby("City")["Salary"].sum().idxmax()
common_city = df.groupby("City")["Salary"].median().idxmax()

print("\nBest Paying City:",highest_paying_city)
print("Most Common City:",common_city)

missing_values = df.isna().sum()
duplicate_rows = df.duplicated().sum()

print("\nMissing Values:\n",missing_values)
print("Duplicate Rows:",duplicate_rows)

==================================================
CUSTOMER DATA REPORT
==================================================

Total Customers: 7
Average Age: 27.29
Average Salary: 58333.33

Highest Salary: 72000.0
Highest Paid Customer: Vikas

Best Paying City: Mumbai
Most Common City: Mumbai

Missing Values:
 Customer_ID    0
Name           0
City           0
Age            0
Salary         0
dtype: int64
Duplicate Rows: 0