In [1]:
import pandas as pd

In [44]:
df = pd.read_csv("employees.csv")
df

,Employee_ID,Name,Department,City,Experience,Salary,Python,SQL,ML
0,101,Amit,Data,Pune,2,55000,78,82,75
1,102,Sneha,Data,Mumbai,4,75000,88,91,84
2,103,Rahul,Engineering,Delhi,6,95000,72,85,89
3,104,Priya,Data,Pune,3,68000,91,87,90
4,105,Vikas,Engineering,Mumbai,8,120000,85,92,94
5,106,Neha,Analytics,Delhi,5,85000,95,89,91
6,107,Arjun,Analytics,Pune,2,58000,82,78,80
7,108,Kiran,Engineering,Mumbai,7,110000,76,88,92
8,109,Riya,Data,Delhi,1,48000,89,84,79
9,110,Rohit,Analytics,Pune,4,72000,93,90,88

In [45]:
df["Department"] = df["Department"].map(
    str.upper
)
df["Department"]

0           DATA
1           DATA
2    ENGINEERING
3           DATA
4    ENGINEERING
5      ANALYTICS
6      ANALYTICS
7    ENGINEERING
8           DATA
9      ANALYTICS
Name: Department, dtype: str

In [41]:
department_codes = {
    "Data": "DAT",
    "Engineering": "ENG",
    "Analytics": "ANA"
}

In [42]:
df["Department"] = df["Department"].map(
    department_codes
)

In [46]:
df

,Employee_ID,Name,Department,City,Experience,Salary,Python,SQL,ML
0,101,Amit,DATA,Pune,2,55000,78,82,75
1,102,Sneha,DATA,Mumbai,4,75000,88,91,84
2,103,Rahul,ENGINEERING,Delhi,6,95000,72,85,89
3,104,Priya,DATA,Pune,3,68000,91,87,90
4,105,Vikas,ENGINEERING,Mumbai,8,120000,85,92,94
5,106,Neha,ANALYTICS,Delhi,5,85000,95,89,91
6,107,Arjun,ANALYTICS,Pune,2,58000,82,78,80
7,108,Kiran,ENGINEERING,Mumbai,7,110000,76,88,92
8,109,Riya,DATA,Delhi,1,48000,89,84,79
9,110,Rohit,ANALYTICS,Pune,4,72000,93,90,88

In [47]:
df["City"] = df["City"].replace(
    {
        "Mumbai": "BOM",
        "Pune": "PNQ",
        "Delhi": "DEL"
    }
)
df["City"]

0    PNQ
1    BOM
2    DEL
3    PNQ
4    BOM
5    DEL
6    PNQ
7    BOM
8    DEL
9    PNQ
Name: City, dtype: str

In [48]:
df["Skill_Average"] = df[
    ["Python", "SQL", "ML"]
].mean(axis=1)

df["Skill_Average"] = (
    df["Skill_Average"].round(2)
)

In [49]:
def performance(score):

    if score >= 90:
        return "Excellent"

    elif score >= 80:
        return "Good"
    
    elif score >= 70:
        return "Average"

    else:
        return "Needs Improvement"

In [50]:
df["Performance"] = df[
    "Skill_Average"
].apply(performance)

In [51]:
df[["Name", "Skill_Average", "Performance"]]

    Name  Skill_Average Performance
0   Amit          78.33     Average
1  Sneha          87.67        Good
2  Rahul          82.00        Good
3  Priya          89.33        Good
4  Vikas          90.33   Excellent
5   Neha          91.67   Excellent
6  Arjun          80.00        Good
7  Kiran          85.33        Good
8   Riya          84.00        Good
9  Rohit          90.33   Excellent

In [52]:
df["Experience_Level"] = df[
    "Experience"
].apply(
    lambda x: "Senior" if x >= 5 else "Junior"
)

In [53]:
df

,Employee_ID,Name,Department,City,Experience,Salary,Python,SQL,ML,Skill_Average,Performance,Experience_Level
0,101,Amit,DATA,PNQ,2,55000,78,82,75,78.33,Average,Junior
1,102,Sneha,DATA,BOM,4,75000,88,91,84,87.67,Good,Junior
2,103,Rahul,ENGINEERING,DEL,6,95000,72,85,89,82.00,Good,Senior
3,104,Priya,DATA,PNQ,3,68000,91,87,90,89.33,Good,Junior
4,105,Vikas,ENGINEERING,BOM,8,120000,85,92,94,90.33,Excellent,Senior
5,106,Neha,ANALYTICS,DEL,5,85000,95,89,91,91.67,Excellent,Senior
6,107,Arjun,ANALYTICS,PNQ,2,58000,82,78,80,80.00,Good,Junior
7,108,Kiran,ENGINEERING,BOM,7,110000,76,88,92,85.33,Good,Senior
8,109,Riya,DATA,DEL,1,48000,89,84,79,84.00,Good,Junior
9,110,Rohit,ANALYTICS,PNQ,4,72000,93,90,88,90.33,Excellent,Junior

In [54]:
department_avg = df.groupby(
    "Department"
)["Salary"].transform("mean")
department_avg

0     61500.000000
1     61500.000000
2    108333.333333
3     61500.000000
4    108333.333333
5     71666.666667
6     71666.666667
7    108333.333333
8     61500.000000
9     71666.666667
Name: Salary, dtype: float64

In [55]:
df["Department_Avg_Salary"] = (
    department_avg.round(2)
)

In [56]:
df[
    [
        "Name",
        "Department",
        "Salary",
        "Department_Avg_Salary"
    ]
]

    Name   Department  Salary  Department_Avg_Salary
0   Amit         DATA   55000               61500.00
1  Sneha         DATA   75000               61500.00
2  Rahul  ENGINEERING   95000              108333.33
3  Priya         DATA   68000               61500.00
4  Vikas  ENGINEERING  120000              108333.33
5   Neha    ANALYTICS   85000               71666.67
6  Arjun    ANALYTICS   58000               71666.67
7  Kiran  ENGINEERING  110000              108333.33
8   Riya         DATA   48000               61500.00
9  Rohit    ANALYTICS   72000               71666.67

In [57]:
df["Salary_vs_Department_Avg"] = (
    df["Salary"]
    - df["Department_Avg_Salary"]
)

In [58]:
df["Salary_vs_Department_Avg"] = (
    df["Salary_vs_Department_Avg"]
    .round(2)
)
df

,Employee_ID,Name,Department,City,Experience,Salary,Python,SQL,ML,Skill_Average,Performance,Experience_Level,Department_Avg_Salary,Salary_vs_Department_Avg
0,101,Amit,DATA,PNQ,2,55000,78,82,75,78.33,Average,Junior,61500.00,-6500.00
1,102,Sneha,DATA,BOM,4,75000,88,91,84,87.67,Good,Junior,61500.00,13500.00
2,103,Rahul,ENGINEERING,DEL,6,95000,72,85,89,82.00,Good,Senior,108333.33,-13333.33
3,104,Priya,DATA,PNQ,3,68000,91,87,90,89.33,Good,Junior,61500.00,6500.00
4,105,Vikas,ENGINEERING,BOM,8,120000,85,92,94,90.33,Excellent,Senior,108333.33,11666.67
5,106,Neha,ANALYTICS,DEL,5,85000,95,89,91,91.67,Excellent,Senior,71666.67,13333.33
6,107,Arjun,ANALYTICS,PNQ,2,58000,82,78,80,80.00,Good,Junior,71666.67,-13666.67
7,108,Kiran,ENGINEERING,BOM,7,110000,76,88,92,85.33,Good,Senior,108333.33,1666.67
8,109,Riya,DATA,DEL,1,48000,89,84,79,84.00,Good,Junior,61500.00,-13500.00
9,110,Rohit,ANALYTICS,PNQ,4,72000,93,90,88,90.33,Excellent,Junior,71666.67,333.33

In [59]:
df["Salary_Rank"] = (
    df["Salary"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [60]:
df[
    ["Name", "Salary", "Salary_Rank"]
].sort_values("Salary_Rank")

    Name  Salary  Salary_Rank
4  Vikas  120000          1.0
7  Kiran  110000          2.0
2  Rahul   95000          3.0
5   Neha   85000          4.0
1  Sneha   75000          5.0
9  Rohit   72000          6.0
3  Priya   68000          7.0
6  Arjun   58000          8.0
0   Amit   55000          9.0
8   Riya   48000         10.0

In [61]:
df["Skill_Rank"] = (
    df["Skill_Average"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [63]:
df[
    ["Name", "Skill_Average", "Skill_Rank"]
].sort_values("Skill_Rank")

    Name  Skill_Average  Skill_Rank
5   Neha          91.67         1.0
4  Vikas          90.33         2.0
9  Rohit          90.33         2.0
3  Priya          89.33         3.0
1  Sneha          87.67         4.0
7  Kiran          85.33         5.0
8   Riya          84.00         6.0
2  Rahul          82.00         7.0
6  Arjun          80.00         8.0
0   Amit          78.33         9.0

In [64]:
df["Experience_Level"] = pd.cut(
    df["Experience"],
    bins=[0, 2, 5, 100],
    labels=[
        "Junior",
        "Mid-Level",
        "Senior"
    ]
)

In [65]:
df[
    ["Name", "Experience", "Experience_Level"]
]

    Name  Experience Experience_Level
0   Amit           2           Junior
1  Sneha           4        Mid-Level
2  Rahul           6           Senior
3  Priya           3        Mid-Level
4  Vikas           8           Senior
5   Neha           5        Mid-Level
6  Arjun           2           Junior
7  Kiran           7           Senior
8   Riya           1           Junior
9  Rohit           4        Mid-Level

In [66]:
df["Salary_Band"] = pd.cut(
    df["Salary"],
    bins=[0, 60000, 90000, 150000],
    labels=[
        "Low",
        "Medium",
        "High"
    ]
)

In [67]:
df[
        [
            "Name",
            "Salary",
            "Salary_Band"
        ]
    ]

    Name  Salary Salary_Band
0   Amit   55000         Low
1  Sneha   75000      Medium
2  Rahul   95000        High
3  Priya   68000      Medium
4  Vikas  120000        High
5   Neha   85000      Medium
6  Arjun   58000         Low
7  Kiran  110000        High
8   Riya   48000         Low
9  Rohit   72000      Medium