In [2]:
import pandas as pd

 -------------------------
Load data

In [3]:
df = pd.read_csv("sales_data.csv")

 -------------------------
 Region sales

In [21]:
region_sales = (
    df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("\n===== REGION SALES =====")
region_sales

===== REGION SALES =====

Region
West     185000
South    128100
North     92000
Name: Sales, dtype: int64

 -------------------------
 Pivot: Region × Category

In [22]:
region_category = pd.pivot_table(
    df,
    index="Region",
    columns="Category",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

print("\n===== REGION × CATEGORY =====")
region_category

===== REGION × CATEGORY =====

Category  Accessories  Electronics
Region
North           12000        80000
South            5100       123000
West             8000       177000

 -------------------------
 Pivot with total

In [23]:
region_category_total = pd.pivot_table(
    df,
    index="Region",
    columns="Category",
    values="Sales",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

print("\n===== REGION × CATEGORY WITH TOTALS =====")
region_category_total

===== REGION × CATEGORY WITH TOTALS =====

Category  Accessories  Electronics     All
Region
North           12000        80000   92000
South            5100       123000  128100
West             8000       177000  185000
All             25100       380000  405100

 -------------------------
 Product × Region

In [24]:
product_region = pd.pivot_table(
    df,
    index="Product",
    columns="Region",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

print("\n===== PRODUCT × REGION =====")
product_region

===== PRODUCT × REGION =====

Region      North  South    West
Product
Headphones   5500      0    5000
Keyboard     3200   3500    3000
Laptop      80000  70000  147000
Monitor         0  53000   30000
Mouse        3300   1600       0

 -------------------------
 Order count using crosstab

In [26]:
order_count = pd.crosstab(
    df["Region"],
    df["Category"],
    margins=True
)

print("\n===== ORDER COUNT =====")
order_count

===== ORDER COUNT =====

Category  Accessories  Electronics  All
Region
North               4            1    5
South               2            3    5
West                2            3    5
All                 8            7   15

 -------------------------
 Percentage distribution

In [28]:
percentage = pd.crosstab(
    df["Region"],
    df["Category"],
    normalize="index"
)

print("\n===== CATEGORY PERCENTAGE BY REGION =====")
percentage

===== CATEGORY PERCENTAGE BY REGION =====

Category  Accessories  Electronics
Region
North             0.8          0.2
South             0.4          0.6
West              0.4          0.6

 -------------------------
 Best combinations

In [29]:
ranking = (
    region_category
    .stack()
    .sort_values(ascending=False)
)

print("\n===== BEST REGION-CATEGORY COMBINATIONS =====")
ranking

===== BEST REGION-CATEGORY COMBINATIONS =====

Region  Category
West    Electronics    177000
South   Electronics    123000
North   Electronics     80000
        Accessories     12000
West    Accessories      8000
South   Accessories      5100
dtype: int64

 -------------------------
 Export

In [30]:
region_category_total.to_csv(
    "region_category_sales.csv"
)

print("\nReport exported successfully.")

Report exported successfully.