In [1]:
import pandas as pd

 -------------------------
 1. Read CSV
 -------------------------

In [2]:
df = pd.read_csv("sales_data.csv")

In [29]:
print("===== DATASET =====")
df

===== DATASET =====

,Order_ID,Product,Category,Region,Sales,Quantity,Rating,Sales_Per_Unit
0,1001,Laptop,Electronics,West,75000,2,4.5,37500.00
1,1002,Mouse,Accessories,North,1500,5,4.1,300.00
2,1003,Keyboard,Accessories,West,3000,3,4.3,1000.00
3,1004,Monitor,Electronics,South,25000,2,4.6,12500.00
4,1005,Laptop,Electronics,North,80000,2,4.7,40000.00
5,1006,Headphones,Accessories,West,5000,4,4.2,1250.00
6,1007,Keyboard,Accessories,South,3500,3,4.0,1166.67
7,1008,Monitor,Electronics,West,30000,2,4.8,15000.00
8,1009,Mouse,Accessories,North,1800,6,4.4,300.00
9,1010,Laptop,Electronics,South,70000,2,4.5,35000.00
10,1011,Headphones,Accessories,North,5500,5,4.1,1100.00
11,1012,Monitor,Electronics,South,28000,2,4.6,14000.00

 -------------------------
 2. Basic Information
 -------------------------

In [4]:
df.head()

   Order_ID   Product     Category Region  Sales  Quantity  Rating
0      1001    Laptop  Electronics   West  75000         2     4.5
1      1002     Mouse  Accessories  North   1500         5     4.1
2      1003  Keyboard  Accessories   West   3000         3     4.3
3      1004   Monitor  Electronics  South  25000         2     4.6
4      1005    Laptop  Electronics  North  80000         2     4.7

In [5]:
df.tail()

    Order_ID     Product     Category Region  Sales  Quantity  Rating
7       1008     Monitor  Electronics   West  30000         2     4.8
8       1009       Mouse  Accessories  North   1800         6     4.4
9       1010      Laptop  Electronics  South  70000         2     4.5
10      1011  Headphones  Accessories  North   5500         5     4.1
11      1012     Monitor  Electronics  South  28000         2     4.6

In [6]:
df.shape

(12, 7)

In [7]:
df.columns

Index(['Order_ID', 'Product', 'Category', 'Region', 'Sales', 'Quantity',
       'Rating'],
      dtype='str')

In [8]:
df.dtypes

Order_ID      int64
Product         str
Category        str
Region          str
Sales         int64
Quantity      int64
Rating      float64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  12 non-null     int64
 1   Product   12 non-null     str
 2   Category  12 non-null     str
 3   Region    12 non-null     str
 4   Sales     12 non-null     int64
 5   Quantity  12 non-null     int64
 6   Rating    12 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 804.0 bytes

In [10]:
df.describe()

          Order_ID         Sales   Quantity    Rating
count    12.000000     12.000000  12.000000  12.00000
mean   1006.500000  27358.333333   3.166667   4.40000
std       3.605551  30650.892270   1.466804   0.25937
min    1001.000000   1500.000000   2.000000   4.00000
25%    1003.750000   3375.000000   2.000000   4.17500
50%    1006.500000  15250.000000   2.500000   4.45000
75%    1009.250000  40000.000000   4.250000   4.60000
max    1012.000000  80000.000000   6.000000   4.80000

Select Data

In [11]:
print(df["Product"])

0         Laptop
1          Mouse
2       Keyboard
3        Monitor
4         Laptop
5     Headphones
6       Keyboard
7        Monitor
8          Mouse
9         Laptop
10    Headphones
11       Monitor
Name: Product, dtype: str

In [12]:
print(df[["Product", "Sales", "Rating"]])

       Product  Sales  Rating
0       Laptop  75000     4.5
1        Mouse   1500     4.1
2     Keyboard   3000     4.3
3      Monitor  25000     4.6
4       Laptop  80000     4.7
5   Headphones   5000     4.2
6     Keyboard   3500     4.0
7      Monitor  30000     4.8
8        Mouse   1800     4.4
9       Laptop  70000     4.5
10  Headphones   5500     4.1
11     Monitor  28000     4.6

 -------------------------
 3. High Sales
 -------------------------

In [13]:
high_sales = df[df["Sales"] > 30000]
print(high_sales)

   Order_ID Product     Category Region  Sales  Quantity  Rating
0      1001  Laptop  Electronics   West  75000         2     4.5
4      1005  Laptop  Electronics  North  80000         2     4.7
9      1010  Laptop  Electronics  South  70000         2     4.5

 -------------------------
 4. Electronics
 -------------------------

In [30]:
electronics = df[df["Category"] == "Electronics"]

print("\n===== ELECTRONICS =====")
print(electronics)

===== ELECTRONICS =====
    Order_ID  Product     Category Region  Sales  Quantity  Rating  \
0       1001   Laptop  Electronics   West  75000         2     4.5
3       1004  Monitor  Electronics  South  25000         2     4.6
4       1005   Laptop  Electronics  North  80000         2     4.7
7       1008  Monitor  Electronics   West  30000         2     4.8
9       1010   Laptop  Electronics  South  70000         2     4.5
11      1012  Monitor  Electronics  South  28000         2     4.6

    Sales_Per_Unit
0          37500.0
3          12500.0
4          40000.0
7          15000.0
9          35000.0
11         14000.0

In [15]:
west = df[df["Region"] == "West"]
print(west)

   Order_ID     Product     Category Region  Sales  Quantity  Rating
0      1001      Laptop  Electronics   West  75000         2     4.5
2      1003    Keyboard  Accessories   West   3000         3     4.3
5      1006  Headphones  Accessories   West   5000         4     4.2
7      1008     Monitor  Electronics   West  30000         2     4.8

 -------------------------
 5. Calculated Column
 -------------------------

In [18]:
df["Sales_Per_Unit"] = df["Sales"] / df["Quantity"]
df["Sales_Per_Unit"] = df["Sales_Per_Unit"].round(2)

In [19]:
print(df[["Product", "Sales", "Quantity", "Sales_Per_Unit"]])

       Product  Sales  Quantity  Sales_Per_Unit
0       Laptop  75000         2        37500.00
1        Mouse   1500         5          300.00
2     Keyboard   3000         3         1000.00
3      Monitor  25000         2        12500.00
4       Laptop  80000         2        40000.00
5   Headphones   5000         4         1250.00
6     Keyboard   3500         3         1166.67
7      Monitor  30000         2        15000.00
8        Mouse   1800         6          300.00
9       Laptop  70000         2        35000.00
10  Headphones   5500         5         1100.00
11     Monitor  28000         2        14000.00

GroupBy — Real Analysis

Total sales by region:

In [20]:
region_sales = df.groupby("Region")["Sales"].sum()
print(region_sales)

Region
North     88800
South    126500
West     113000
Name: Sales, dtype: int64

Total sales by category:

In [21]:
category_sales = df.groupby("Category")["Sales"].sum()
print(category_sales)

Category
Accessories     20300
Electronics    308000
Name: Sales, dtype: int64

Average rating by category:

In [22]:
category_rating = df.groupby("Category")["Rating"].mean()
print(category_rating)

Category
Accessories    4.183333
Electronics    4.616667
Name: Rating, dtype: float64

 -------------------------
 6. Region Analysis
 -------------------------

In [31]:
report = df.groupby("Region").agg(
    Total_Sales = ("Sales", "sum"),
    Average_Sales = ("Sales", "mean"),
    Total_Quantity = ("Quantity", "sum"),
    Avearge_Rating = ("Rating", "mean")
)

print("\n===== REGION REPORT =====")
print(report)

===== REGION REPORT =====
        Total_Sales  Average_Sales  Total_Quantity  Avearge_Rating
Region
North         88800        22200.0              18           4.325
South        126500        31625.0               9           4.425
West         113000        28250.0              11           4.450

 -------------------------
 7. Product Ranking
 -------------------------

In [26]:
product_sales = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)

print(product_sales)
print(product_sales.head(1))

Product
Laptop        225000
Monitor        83000
Headphones     10500
Keyboard        6500
Mouse           3300
Name: Sales, dtype: int64
Product
Laptop    225000
Name: Sales, dtype: int64

 -------------------------
 8. Export
 -------------------------

In [28]:
df.to_csv("cleaned_sales_data.csv", index=False)