In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_data.csv")

 -------------------------
 1. Inspection
 -------------------------

In [3]:
df.shape

(12, 7)

In [4]:
df.columns

Index(['Order_ID', 'Product', 'Category', 'Region', 'Sales', 'Quantity',
       'Rating'],
      dtype='str')

In [5]:
df.dtypes

Order_ID      int64
Product         str
Category        str
Region          str
Sales         int64
Quantity      int64
Rating      float64
dtype: object

In [6]:
df.head()

   Order_ID   Product     Category Region  Sales  Quantity  Rating
0      1001    Laptop  Electronics   West  75000         2     4.5
1      1002     Mouse  Accessories  North   1500         5     4.1
2      1003  Keyboard  Accessories   West   3000         3     4.3
3      1004   Monitor  Electronics  South  25000         2     4.6
4      1005    Laptop  Electronics  North  80000         2     4.7

In [7]:
df.tail(3)

    Order_ID     Product     Category Region  Sales  Quantity  Rating
9       1010      Laptop  Electronics  South  70000         2     4.5
10      1011  Headphones  Accessories  North   5500         5     4.1
11      1012     Monitor  Electronics  South  28000         2     4.6

In [8]:
df.describe()

          Order_ID         Sales   Quantity    Rating
count    12.000000     12.000000  12.000000  12.00000
mean   1006.500000  27358.333333   3.166667   4.40000
std       3.605551  30650.892270   1.466804   0.25937
min    1001.000000   1500.000000   2.000000   4.00000
25%    1003.750000   3375.000000   2.000000   4.17500
50%    1006.500000  15250.000000   2.500000   4.45000
75%    1009.250000  40000.000000   4.250000   4.60000
max    1012.000000  80000.000000   6.000000   4.80000

 -------------------------
 2. Filtering
 -------------------------

1. Sales greater than ₹50,000

In [9]:
higher_sales = df[df["Sales"] > 50000]

print(higher_sales)

   Order_ID Product     Category Region  Sales  Quantity  Rating
0      1001  Laptop  Electronics   West  75000         2     4.5
4      1005  Laptop  Electronics  North  80000         2     4.7
9      1010  Laptop  Electronics  South  70000         2     4.5

2. Rating greater than 4.5

In [10]:
high_rating = df[df["Rating"] > 4.5]
print(high_rating)

    Order_ID  Product     Category Region  Sales  Quantity  Rating
3       1004  Monitor  Electronics  South  25000         2     4.6
4       1005   Laptop  Electronics  North  80000         2     4.7
7       1008  Monitor  Electronics   West  30000         2     4.8
11      1012  Monitor  Electronics  South  28000         2     4.6

3. Electronics products

In [11]:
electronics = df[df["Category"] == "Electronics"]
print(electronics)

    Order_ID  Product     Category Region  Sales  Quantity  Rating
0       1001   Laptop  Electronics   West  75000         2     4.5
3       1004  Monitor  Electronics  South  25000         2     4.6
4       1005   Laptop  Electronics  North  80000         2     4.7
7       1008  Monitor  Electronics   West  30000         2     4.8
9       1010   Laptop  Electronics  South  70000         2     4.5
11      1012  Monitor  Electronics  South  28000         2     4.6

4. West region

In [12]:
west = df[df["Region"] == "West"]
print(west)

   Order_ID     Product     Category Region  Sales  Quantity  Rating
0      1001      Laptop  Electronics   West  75000         2     4.5
2      1003    Keyboard  Accessories   West   3000         3     4.3
5      1006  Headphones  Accessories   West   5000         4     4.2
7      1008     Monitor  Electronics   West  30000         2     4.8

5. Quantity greater than 3

In [13]:
high_quantity = df[df["Quantity"] > 3]
print(high_quantity)

    Order_ID     Product     Category Region  Sales  Quantity  Rating
1       1002       Mouse  Accessories  North   1500         5     4.1
5       1006  Headphones  Accessories   West   5000         4     4.2
8       1009       Mouse  Accessories  North   1800         6     4.4
10      1011  Headphones  Accessories  North   5500         5     4.1

 -------------------------
 3. Calculations
 -------------------------

In [14]:
df["Sales_Per_Unit"] = df["Sales"] / df["Quantity"]
df["Sales_Per_Unit"] = df["Sales_Per_Unit"].round(2)

In [17]:
print("Highest Sales Per Unit:",df["Sales_Per_Unit"].max())
print("Lowest Sales Per Unit:",df["Sales_Per_Unit"].min())
print("Average Sales Per Unit:",round(df["Sales_Per_Unit"].mean(), 2))

Highest Sales Per Unit: 40000.0
Lowest Sales Per Unit: 300.0
Average Sales Per Unit: 13259.72

 -------------------------
 4. GroupBy
 -------------------------

Total sales by Region

In [18]:
df.groupby("Region")["Sales"].sum()

Region
North     88800
South    126500
West     113000
Name: Sales, dtype: int64

Total sales by Category

In [20]:
df.groupby("Category")["Sales"].sum()

Category
Accessories     20300
Electronics    308000
Name: Sales, dtype: int64

Average rating by Region

In [19]:
df.groupby("Region")["Rating"].mean()

Region
North    4.325
South    4.425
West     4.450
Name: Rating, dtype: float64

Total quantity by Product

In [21]:
df.groupby("Product")["Quantity"].sum()

Product
Headphones     9
Keyboard       6
Laptop         6
Monitor        6
Mouse         11
Name: Quantity, dtype: int64

 -------------------------
 5. Ranking
 -------------------------

Top 3 products by total sales

In [22]:
df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(3)

Product
Laptop        225000
Monitor        83000
Headphones     10500
Name: Sales, dtype: int64

 -------------------------
 6. Regional Sales Report
 -------------------------

In [28]:
report = df.groupby("Region").agg(
    Total_Sales = ("Sales", "sum"),
    Average_Sales = ("Sales", "mean"),
    Total_Quantity = ("Quantity", "sum"),
    Average_Rating = ("Rating", "mean"),
    Number_of_Orders = ("Order_ID", "count")
)
report

,Total_Sales,Average_Sales,Total_Quantity,Average_Rating,Number_of_Orders
Region,,,,,
North,88800,22200.0,18,4.325,4
South,126500,31625.0,9,4.425,4
West,113000,28250.0,11,4.450,4

1. Sort by Total Sales

In [30]:
report = report.sort_values("Total_Sales", ascending=False)
report

,Total_Sales,Average_Sales,Total_Quantity,Average_Rating,Number_of_Orders
Region,,,,,
South,126500,31625.0,9,4.425,4
West,113000,28250.0,11,4.450,4
North,88800,22200.0,18,4.325,4

2. Export it

In [31]:
report.to_csv("regional_sales_report.csv")