In [1]:
import pandas as pd

In [2]:
data = {
    "Employee": [
        "Amit", "Sneha", "Rahul", "Priya", "Vikas",
        "Neha", "Arjun", "Pooja", "Karan", "Riya"
    ],

    "Department": [
        "Data", "Data", "IT", "HR", "IT",
        "Data", "HR", "IT", "Data", "IT"
    ],

    "City": [
        "Pune", "Mumbai", "Pune", "Delhi", "Mumbai",
        "Pune", "Delhi", "Mumbai", "Pune", "Delhi"
    ],

    "Salary": [
        70000, 85000, 65000, 55000, 75000,
        90000, 60000, 80000, 72000, 68000
    ],

    "Experience": [
        2, 3, 1, 2, 3,
        4, 2, 3, 2, 1
    ]
}

df = pd.DataFrame(data)

In [4]:
df

  Employee Department    City  Salary  Experience
0     Amit       Data    Pune   70000           2
1    Sneha       Data  Mumbai   85000           3
2    Rahul         IT    Pune   65000           1
3    Priya         HR   Delhi   55000           2
4    Vikas         IT  Mumbai   75000           3
5     Neha       Data    Pune   90000           4
6    Arjun         HR   Delhi   60000           2
7    Pooja         IT  Mumbai   80000           3
8    Karan       Data    Pune   72000           2
9     Riya         IT   Delhi   68000           1

1. Find the average salary by department.

In [5]:
df.groupby("Department")["Salary"].mean()

Department
Data    79250.0
HR      57500.0
IT      72000.0
Name: Salary, dtype: float64

2. Find the maximum salary by department.

In [6]:
df.groupby("Department")["Salary"].max()

Department
Data    90000
HR      60000
IT      80000
Name: Salary, dtype: int64

3. Find the minimum salary by department.

In [7]:
df.groupby("Department")["Salary"].min()

Department
Data    70000
HR      55000
IT      65000
Name: Salary, dtype: int64

4. Count the number of employees in each department.

In [8]:
df.groupby("Department")["Employee"].count()

Department
Data    4
HR      2
IT      4
Name: Employee, dtype: int64

5. Calculate:\
Total Salary\
Average Salary\
Minimum Salary\
Maximum Salary

In [10]:
df.groupby("Department").agg(
    Total_Salary=("Salary", "sum"),
    Average_Salary=("Salary", "mean"),
    Minimum_Salary=("Salary", "min"),
    Maximum_Salary=("Salary", "max"),
)

            Total_Salary  Average_Salary  Minimum_Salary  Maximum_Salary
Department
Data              317000         79250.0           70000           90000
HR                115000         57500.0           55000           60000
IT                288000         72000.0           65000           80000

6. Find average salary by city.

In [11]:
df.groupby("City")["Salary"].mean()

City
Delhi     61000.0
Mumbai    80000.0
Pune      74250.0
Name: Salary, dtype: float64

7. Find average salary by:\
Department + City

In [14]:
df.groupby(["Department","City"])["Salary"].mean()

Department  City
Data        Mumbai    85000.000000
            Pune      77333.333333
HR          Delhi     57500.000000
IT          Delhi     68000.000000
            Mumbai    77500.000000
            Pune      65000.000000
Name: Salary, dtype: float64

8. Find the department with the highest total salary.

In [16]:
department_salary = df.groupby("Department")["Salary"].sum().idxmax()
print(department_salary)

Data

9. Find the department with the highest average salary.

In [18]:
department_avg_salary = df.groupby("Department")["Salary"].mean().idxmax()
print(department_avg_salary)

Data

10. Create a department report:\
Department\
Total Employees\
Total Salary\
Average Salary\
Average Experience\
Maximum Salary

In [19]:
department_report = (
    df.groupby("Department")
    .agg(
        Total_Employees = ("Salary", "count"),
        Total_Salary = ("Salary", "sum"),
        Average_Salary = ("Salary", "mean"),
        Average_Experience = ("Experience", "mean"),
        Maximum_Salary = ("Salary", "max")
    )
)

print(department_report)

            Total_Employees  Total_Salary  Average_Salary  Average_Experience  \
Department
Data                      4        317000         79250.0                2.75
HR                        2        115000         57500.0                2.00
IT                        4        288000         72000.0                2.00

            Maximum_Salary
Department
Data                 90000
HR                   60000
IT                   80000

Which department has the highest total salary, at least 3 employees, and an average salary above ₹70,000?

In [20]:
dept_summary = df.groupby("Department").agg(
    Total_Employees = ("Salary", "count"),
    Total_Salary = ("Salary", "sum"),
    Average_Salary = ("Salary", "mean")
)

In [21]:
filter = (dept_summary["Total_Employees"] > 3) & (dept_summary["Average_Salary"] > 70000)

In [23]:
print(dept_summary[filter].sort_values("Total_Salary", ascending=False))

            Total_Employees  Total_Salary  Average_Salary
Department
Data                      4        317000         79250.0
IT                        4        288000         72000.0