In [1]:
import pandas as pd

In [2]:
data = {
    "Product": [
        "Laptop", "Phone", "Tablet", "Monitor",
        "Keyboard", "Mouse", "Laptop", "Phone",
        "Monitor", "Tablet"
    ],
    "Category": [
        "Electronics", "Electronics", "Electronics",
        "Electronics", "Accessories", "Accessories",
        "Electronics", "Electronics",
        "Electronics", "Electronics"
    ],
    "Price": [
        65000, 30000, 25000, 18000, 2500,
        1200, 72000, 35000, 20000, 28000
    ],
    "Quantity": [
        2, 5, 3, 4, 10,
        15, 1, 4, 2, 3
    ],
    "Rating": [
        4.5, 4.2, 4.0, 4.4, 4.1,
        3.9, 4.7, 4.3, 4.5, 4.1
    ]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

    Product     Category  Price  Quantity  Rating
0    Laptop  Electronics  65000         2     4.5
1     Phone  Electronics  30000         5     4.2
2    Tablet  Electronics  25000         3     4.0
3   Monitor  Electronics  18000         4     4.4
4  Keyboard  Accessories   2500        10     4.1
5     Mouse  Accessories   1200        15     3.9
6    Laptop  Electronics  72000         1     4.7
7     Phone  Electronics  35000         4     4.3
8   Monitor  Electronics  20000         2     4.5
9    Tablet  Electronics  28000         3     4.1

1. Display the first 5 rows.

In [5]:
df.head(5)

    Product     Category  Price  Quantity  Rating
0    Laptop  Electronics  65000         2     4.5
1     Phone  Electronics  30000         5     4.2
2    Tablet  Electronics  25000         3     4.0
3   Monitor  Electronics  18000         4     4.4
4  Keyboard  Accessories   2500        10     4.1

2. Display only:\
Product\
Price\
Rating

In [6]:
df[["Product","Price","Rating"]]

    Product  Price  Rating
0    Laptop  65000     4.5
1     Phone  30000     4.2
2    Tablet  25000     4.0
3   Monitor  18000     4.4
4  Keyboard   2500     4.1
5     Mouse   1200     3.9
6    Laptop  72000     4.7
7     Phone  35000     4.3
8   Monitor  20000     4.5
9    Tablet  28000     4.1

3.Find products with:\
Price > 25000

In [9]:
df[df["Price"] > 25000]

  Product     Category  Price  Quantity  Rating
0  Laptop  Electronics  65000         2     4.5
1   Phone  Electronics  30000         5     4.2
6  Laptop  Electronics  72000         1     4.7
7   Phone  Electronics  35000         4     4.3
9  Tablet  Electronics  28000         3     4.1

4.Find products with:\
Rating >= 4.5

In [10]:
df[df["Rating"] > 4.5]

  Product     Category  Price  Quantity  Rating
6  Laptop  Electronics  72000         1     4.7

5.Find products where:\
Price > 20000\
AND Rating >= 4.3

In [11]:
df[
    (df["Price"] > 20000) &
    (df["Rating"] > 4.3)
]

  Product     Category  Price  Quantity  Rating
0  Laptop  Electronics  65000         2     4.5
6  Laptop  Electronics  72000         1     4.7

6. Sort products by price from highest → lowest.

In [12]:
df.sort_values(
    "Price",
    ascending=False
)

    Product     Category  Price  Quantity  Rating
6    Laptop  Electronics  72000         1     4.7
0    Laptop  Electronics  65000         2     4.5
7     Phone  Electronics  35000         4     4.3
1     Phone  Electronics  30000         5     4.2
9    Tablet  Electronics  28000         3     4.1
2    Tablet  Electronics  25000         3     4.0
8   Monitor  Electronics  20000         2     4.5
3   Monitor  Electronics  18000         4     4.4
4  Keyboard  Accessories   2500        10     4.1
5     Mouse  Accessories   1200        15     3.9

7. Create:\
Total_Sales = Price × Quantity

In [13]:
df["Total_Sales"] = df["Price"] * df["Quantity"]

In [15]:
df

    Product     Category  Price  Quantity  Rating  Total_Sales
0    Laptop  Electronics  65000         2     4.5       130000
1     Phone  Electronics  30000         5     4.2       150000
2    Tablet  Electronics  25000         3     4.0        75000
3   Monitor  Electronics  18000         4     4.4        72000
4  Keyboard  Accessories   2500        10     4.1        25000
5     Mouse  Accessories   1200        15     3.9        18000
6    Laptop  Electronics  72000         1     4.7        72000
7     Phone  Electronics  35000         4     4.3       140000
8   Monitor  Electronics  20000         2     4.5        40000
9    Tablet  Electronics  28000         3     4.1        84000

8. Find the product with the highest Total_Sales.

In [18]:
df["Total_Sales"].idxmax()

1

9. Find the average product price.

In [20]:
print(df["Price"].mean())

29670.0

10. Find the number of unique products.

In [21]:
print(df["Product"].nunique())

6

11. Find the number of products sold in each category.

In [22]:
print(df.groupby("Category")["Quantity"].sum())

Category
Accessories    25
Electronics    24
Name: Quantity, dtype: int64

12. Sort the entire dataset by Total_Sales and display the top 3 products.

In [24]:
df.sort_values("Total_Sales",ascending=False).head(3)

  Product     Category  Price  Quantity  Rating  Total_Sales
1   Phone  Electronics  30000         5     4.2       150000
7   Phone  Electronics  35000         4     4.3       140000
0  Laptop  Electronics  65000         2     4.5       130000

Which products generated more than ₹100,000 in total sales, have a rating of at least 4.3, and should be displayed from highest sales to lowest?

In [26]:
result = df[
    (df["Total_Sales"] > 100000) &
    (df["Rating"] >= 4.3)
].sort_values("Total_Sales",ascending=False)
print(result)

  Product     Category  Price  Quantity  Rating  Total_Sales
7   Phone  Electronics  35000         4     4.3       140000
0  Laptop  Electronics  65000         2     4.5       130000