In [28]:
import pandas as pd

 -------------------------
Load Datasets

In [29]:
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")

print("CUSTOMERS")
print(customers)

CUSTOMERS
   Customer_ID   Name    City
0          101   Amit    Pune
1          102  Sneha  Mumbai
2          103  Rahul   Delhi
3          104  Priya    Pune
4          105  Vikas  Mumbai
5          106   Neha  Nashik

In [30]:
print("\nORDERS")
print(orders)

ORDERS
   Order_ID  Customer_ID Product_ID  Quantity
0      5001          101        P01         2
1      5002          102        P02         1
2      5003          101        P03         3
3      5004          103        P01         1
4      5005          105        P02         4
5      5006          102        P03         2
6      5007          101        P02         5
7      5008          104        P01         1
8      5009          103        P03         2

In [31]:
print("\nPRODUCTS")
print(products)

PRODUCTS
  Product_ID   Product     Category  Price
0        P01    Laptop  Electronics  75000
1        P02     Mouse  Accessories   1500
2        P03  Keyboard  Accessories   3000
3        P04   Monitor  Electronics  25000

Merge

In [32]:
customer_order = pd.merge(
    customers,
    orders,
    on="Customer_ID"
)
print(customer_order)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune      5001        P01         2
1          101   Amit    Pune      5003        P03         3
2          101   Amit    Pune      5007        P02         5
3          102  Sneha  Mumbai      5002        P02         1
4          102  Sneha  Mumbai      5006        P03         2
5          103  Rahul   Delhi      5004        P01         1
6          103  Rahul   Delhi      5009        P03         2
7          104  Priya    Pune      5008        P01         1
8          105  Vikas  Mumbai      5005        P02         4

Inner Join

In [33]:
pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="inner"
)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune      5001        P01         2
1          101   Amit    Pune      5003        P03         3
2          101   Amit    Pune      5007        P02         5
3          102  Sneha  Mumbai      5002        P02         1
4          102  Sneha  Mumbai      5006        P03         2
5          103  Rahul   Delhi      5004        P01         1
6          103  Rahul   Delhi      5009        P03         2
7          104  Priya    Pune      5008        P01         1
8          105  Vikas  Mumbai      5005        P02         4

 -------------------------
 Merge customers + orders

In [34]:
customer_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="left"
)
print(customer_orders)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune    5001.0        P01       2.0
1          101   Amit    Pune    5003.0        P03       3.0
2          101   Amit    Pune    5007.0        P02       5.0
3          102  Sneha  Mumbai    5002.0        P02       1.0
4          102  Sneha  Mumbai    5006.0        P03       2.0
5          103  Rahul   Delhi    5004.0        P01       1.0
6          103  Rahul   Delhi    5009.0        P03       2.0
7          104  Priya    Pune    5008.0        P01       1.0
8          105  Vikas  Mumbai    5005.0        P02       4.0
9          106   Neha  Nashik       NaN        NaN       NaN

Right Join

In [35]:
result = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="right"
)
result

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune      5001        P01         2
1          102  Sneha  Mumbai      5002        P02         1
2          101   Amit    Pune      5003        P03         3
3          103  Rahul   Delhi      5004        P01         1
4          105  Vikas  Mumbai      5005        P02         4
5          102  Sneha  Mumbai      5006        P03         2
6          101   Amit    Pune      5007        P02         5
7          104  Priya    Pune      5008        P01         1
8          103  Rahul   Delhi      5009        P03         2

Right Join

In [36]:
result = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="outer"
)
result

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune    5001.0        P01       2.0
1          101   Amit    Pune    5003.0        P03       3.0
2          101   Amit    Pune    5007.0        P02       5.0
3          102  Sneha  Mumbai    5002.0        P02       1.0
4          102  Sneha  Mumbai    5006.0        P03       2.0
5          103  Rahul   Delhi    5004.0        P01       1.0
6          103  Rahul   Delhi    5009.0        P03       2.0
7          104  Priya    Pune    5008.0        P01       1.0
8          105  Vikas  Mumbai    5005.0        P02       4.0
9          106   Neha  Nashik       NaN        NaN       NaN

 -------------------------
 Merge orders + products

In [37]:
order_products = pd.merge(
    orders,
    products,
    on="Product_ID",
    how="left"
)
order_products

   Order_ID  Customer_ID Product_ID  Quantity   Product     Category  Price
0      5001          101        P01         2    Laptop  Electronics  75000
1      5002          102        P02         1     Mouse  Accessories   1500
2      5003          101        P03         3  Keyboard  Accessories   3000
3      5004          103        P01         1    Laptop  Electronics  75000
4      5005          105        P02         4     Mouse  Accessories   1500
5      5006          102        P03         2  Keyboard  Accessories   3000
6      5007          101        P02         5     Mouse  Accessories   1500
7      5008          104        P01         1    Laptop  Electronics  75000
8      5009          103        P03         2  Keyboard  Accessories   3000

 -------------------------
 Calculate sales

In [38]:
order_products["Total_Sales"] = (
    order_products["Quantity"]
    * order_products["Price"]
)

In [39]:
print(
    order_products[
        [
            "Order_ID",
            "Product",
            "Quantity",
            "Price",
            "Total_Sales"
        ]
    ]
)

   Order_ID   Product  Quantity  Price  Total_Sales
0      5001    Laptop         2  75000       150000
1      5002     Mouse         1   1500         1500
2      5003  Keyboard         3   3000         9000
3      5004    Laptop         1  75000        75000
4      5005     Mouse         4   1500         6000
5      5006  Keyboard         2   3000         6000
6      5007     Mouse         5   1500         7500
7      5008    Laptop         1  75000        75000
8      5009  Keyboard         2   3000         6000

 -------------------------
 Full dataset

In [40]:
customer_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="left"
)

In [41]:
full_data = pd.merge(
    customer_orders,
    products,
    on="Product_ID",
    how="left"
)

Calculate revenue:

In [42]:
full_data["Total_Sales"] = (
    full_data["Quantity"]
    * full_data["Price"]
)
full_data

,Customer_ID,Name,City,Order_ID,Product_ID,Quantity,Product,Category,Price,Total_Sales
0,101,Amit,Pune,5001.0,P01,2.0,Laptop,Electronics,75000.0,150000.0
1,101,Amit,Pune,5003.0,P03,3.0,Keyboard,Accessories,3000.0,9000.0
2,101,Amit,Pune,5007.0,P02,5.0,Mouse,Accessories,1500.0,7500.0
3,102,Sneha,Mumbai,5002.0,P02,1.0,Mouse,Accessories,1500.0,1500.0
4,102,Sneha,Mumbai,5006.0,P03,2.0,Keyboard,Accessories,3000.0,6000.0
5,103,Rahul,Delhi,5004.0,P01,1.0,Laptop,Electronics,75000.0,75000.0
6,103,Rahul,Delhi,5009.0,P03,2.0,Keyboard,Accessories,3000.0,6000.0
7,104,Priya,Pune,5008.0,P01,1.0,Laptop,Electronics,75000.0,75000.0
8,105,Vikas,Mumbai,5005.0,P02,4.0,Mouse,Accessories,1500.0,6000.0
9,106,Neha,Nashik,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 -------------------------
 Customer analysis

In [43]:
customer_sales = (
    full_data
    .groupby(["Customer_ID", "Name"])["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)
customer_sales

Customer_ID  Name
101          Amit     166500.0
103          Rahul     81000.0
104          Priya     75000.0
102          Sneha      7500.0
105          Vikas      6000.0
106          Neha          0.0
Name: Total_Sales, dtype: float64

 -------------------------
 City analysis

In [44]:
city_sales = (
    full_data
    .groupby("City")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)
city_sales

City
Pune      241500.0
Delhi      81000.0
Mumbai     13500.0
Nashik         0.0
Name: Total_Sales, dtype: float64

 -------------------------
 Product analysis

In [45]:
product_sales = (
    full_data
    .groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)
product_sales

Product
Laptop      300000.0
Keyboard     21000.0
Mouse        15000.0
Name: Total_Sales, dtype: float64

 -------------------------
 Find customers with no orders

Customers With No Orders

In [46]:
customers_with_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="left"
)
no_orders = customers_with_orders[
    customers_with_orders["Order_ID"].isna()
]
no_orders

   Customer_ID  Name    City  Order_ID Product_ID  Quantity
9          106  Neha  Nashik       NaN        NaN       NaN

 -------------------------
 Export

In [47]:
full_data.to_csv(
    "full_sales_data.csv",
    index=False
)