In [1]:
import pandas as pd

--------
Task 1

In [2]:
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")

In [ ]:
print("Customers:")
print("\nShape:",customers.shape)
print("Columns:",customers.columns)
print("5 Rows:",customers.head())

Customers:

Shape: (6, 3)
Columns: Index(['Customer_ID', 'Name', 'City'], dtype='str')
5 Rows:    Customer_ID   Name    City
0          101   Amit    Pune
1          102  Sneha  Mumbai
2          103  Rahul   Delhi
3          104  Priya    Pune
4          105  Vikas  Mumbai

In [6]:
print("Orders:")
print("\nShape:",orders.shape)
print("Columns:",orders.columns)
print("5 Rows:",orders.head())

Orders:

Shape: (9, 4)
Columns: Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Quantity'], dtype='str')
5 Rows:    Order_ID  Customer_ID Product_ID  Quantity
0      5001          101        P01         2
1      5002          102        P02         1
2      5003          101        P03         3
3      5004          103        P01         1
4      5005          105        P02         4

In [7]:
print("Products:")
print("\nShape:",products.shape)
print("Columns:",products.columns)
print("5 Rows:",products.head())

Products:

Shape: (4, 4)
Columns: Index(['Product_ID', 'Product', 'Category', 'Price'], dtype='str')
5 Rows:   Product_ID   Product     Category  Price
0        P01    Laptop  Electronics  75000
1        P02     Mouse  Accessories   1500
2        P03  Keyboard  Accessories   3000
3        P04   Monitor  Electronics  25000

--------
Task 2

In [8]:
pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="inner"
)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune      5001        P01         2
1          101   Amit    Pune      5003        P03         3
2          101   Amit    Pune      5007        P02         5
3          102  Sneha  Mumbai      5002        P02         1
4          102  Sneha  Mumbai      5006        P03         2
5          103  Rahul   Delhi      5004        P01         1
6          103  Rahul   Delhi      5009        P03         2
7          104  Priya    Pune      5008        P01         1
8          105  Vikas  Mumbai      5005        P02         4

In [10]:
customer_orders = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="left"
)
customer_orders

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune    5001.0        P01       2.0
1          101   Amit    Pune    5003.0        P03       3.0
2          101   Amit    Pune    5007.0        P02       5.0
3          102  Sneha  Mumbai    5002.0        P02       1.0
4          102  Sneha  Mumbai    5006.0        P03       2.0
5          103  Rahul   Delhi    5004.0        P01       1.0
6          103  Rahul   Delhi    5009.0        P03       2.0
7          104  Priya    Pune    5008.0        P01       1.0
8          105  Vikas  Mumbai    5005.0        P02       4.0
9          106   Neha  Nashik       NaN        NaN       NaN

In [11]:
pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="right"
)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune      5001        P01         2
1          102  Sneha  Mumbai      5002        P02         1
2          101   Amit    Pune      5003        P03         3
3          103  Rahul   Delhi      5004        P01         1
4          105  Vikas  Mumbai      5005        P02         4
5          102  Sneha  Mumbai      5006        P03         2
6          101   Amit    Pune      5007        P02         5
7          104  Priya    Pune      5008        P01         1
8          103  Rahul   Delhi      5009        P03         2

In [12]:
pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="outer"
)

   Customer_ID   Name    City  Order_ID Product_ID  Quantity
0          101   Amit    Pune    5001.0        P01       2.0
1          101   Amit    Pune    5003.0        P03       3.0
2          101   Amit    Pune    5007.0        P02       5.0
3          102  Sneha  Mumbai    5002.0        P02       1.0
4          102  Sneha  Mumbai    5006.0        P03       2.0
5          103  Rahul   Delhi    5004.0        P01       1.0
6          103  Rahul   Delhi    5009.0        P03       2.0
7          104  Priya    Pune    5008.0        P01       1.0
8          105  Vikas  Mumbai    5005.0        P02       4.0
9          106   Neha  Nashik       NaN        NaN       NaN

------------
Task 3

In [14]:
product_order = pd.merge(
    orders,
    products,
    on="Product_ID",
    how="left"
)
product_order

   Order_ID  Customer_ID Product_ID  Quantity   Product     Category  Price
0      5001          101        P01         2    Laptop  Electronics  75000
1      5002          102        P02         1     Mouse  Accessories   1500
2      5003          101        P03         3  Keyboard  Accessories   3000
3      5004          103        P01         1    Laptop  Electronics  75000
4      5005          105        P02         4     Mouse  Accessories   1500
5      5006          102        P03         2  Keyboard  Accessories   3000
6      5007          101        P02         5     Mouse  Accessories   1500
7      5008          104        P01         1    Laptop  Electronics  75000
8      5009          103        P03         2  Keyboard  Accessories   3000

-------
Task 4

In [15]:
product_order["Total_Sales"] = product_order["Quantity"] * product_order["Price"]

---------
Task 5

Top customer by spending

In [16]:
product_order.groupby("Customer_ID")["Total_Sales"].sum().sort_values(ascending=False)

Customer_ID
101    166500
103     81000
104     75000
102      7500
105      6000
Name: Total_Sales, dtype: int64

Top product by sales

In [17]:
product_order.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)

Product
Laptop      300000
Keyboard     21000
Mouse        15000
Name: Total_Sales, dtype: int64

Top city by sales

In [19]:
full_data = pd.merge(
    customers,
    product_order,
    on="Customer_ID",
    how="left"
)

In [20]:
full_data.groupby("City")["Total_Sales"].sum().sort_values(ascending=False)

City
Pune      241500.0
Delhi      81000.0
Mumbai     13500.0
Nashik         0.0
Name: Total_Sales, dtype: float64

---------
Task 6

In [22]:
no_order = full_data[full_data["Order_ID"].isna()]
no_order

,Customer_ID,Name,City,Order_ID,Product_ID,Quantity,Product,Category,Price,Total_Sales
9,106,Neha,Nashik,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------
Task 7\
Boss Challenge\
Final Customer Sales Report

In [24]:
report = full_data.groupby(
    ["Customer_ID","Name","City"]
).agg(
    Total_Orders = ("Order_ID", "count"),
    Total_Quantity = ("Quantity", "sum"),
    Total_Sales = ("Total_Sales", "sum")
)

In [25]:
report["Average_Order_Value"] = (
    report["Total_Sales"]
    / report["Total_Orders"]
)

In [26]:
report = report.sort_values(
    "Total_Sales",
    ascending=False
)

In [27]:
report

,,,Total_Orders,Total_Quantity,Total_Sales,Average_Order_Value
Customer_ID,Name,City,,,,
101,Amit,Pune,3,10.0,166500.0,55500.0
103,Rahul,Delhi,2,3.0,81000.0,40500.0
104,Priya,Pune,1,1.0,75000.0,75000.0
102,Sneha,Mumbai,2,3.0,7500.0,3750.0
105,Vikas,Mumbai,1,4.0,6000.0,6000.0
106,Neha,Nashik,0,0.0,0.0,NaN

In [28]:
report.to_csv(
    "customer_sales_report.csv"
)